name: prahar
description: "A personal productivity app for CDS aspirants."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.9.4  # FCM for push notifications

  # State Management
  flutter_riverpod: ^2.5.1

  # UI & Theming
  google_fonts: ^6.2.1
  fl_chart: ^0.67.0
  table_calendar: ^3.1.1
  intl: ^0.19.0

  # Native Features
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.3
  permission_handler: ^11.3.1
  
  # Authentication
  google_sign_in: ^6.2.1

  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_heatmap_calendar: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"